#!/bin/bash
# tests/marker-merge/test.sh
#
# BP-7 regression fixture — verifies `scripts/blueprint pull` performs
# marker-aware merge: it must replace inside-marker content with the
# blueprint's version while keeping outside-marker content byte-identical
# to the project's version.
#
# Two-commit pattern (PLAN-TEST-RELIABILITY §9.1):
#   - This test FAILS on the parent commit (the CLI does whole-file `cp`
#     at line 275 — the project's outside-marker content would be lost).
#   - PASSES on the feat(BP-7) commit that adds marker-aware merge.
#
# Run from the blueprint repo root:
#   bash tests/marker-merge/test.sh
#
# Exit codes: 0 = pass; non-zero = fail.

set -u

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
FIXTURE_DIR="$ROOT/tests/marker-merge"
BP="$FIXTURE_DIR/fixture-blueprint.md"
PROJ_BEFORE="$FIXTURE_DIR/fixture-project-before.md"
EXPECTED="$FIXTURE_DIR/fixture-project-after-expected.md"

# Sanity check the fixtures
for f in "$BP" "$PROJ_BEFORE" "$EXPECTED"; do
  if [ ! -f "$f" ]; then
    echo "FAIL: fixture missing: $f"
    exit 2
  fi
done

# Build a temp "project" directory with a .blueprint-source pointing back
# at the blueprint root, and a single managed file copy.
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT INT TERM

mkdir -p "$WORK/tests/marker-merge"  # mirror layout so the file path
                                     # resolves identically
cp "$PROJ_BEFORE" "$WORK/fixture-target.md"

cat >"$WORK/.blueprint-source" <<EOF
# generated by tests/marker-merge/test.sh
blueprint_source = $ROOT
bootstrap_sha    = $(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "no-sha")
bootstrap_date   = test-fixture
EOF

# Temporarily teach the CLI's MANAGED_FILES that fixture-target.md is
# managed (so `blueprint pull` will consider it). We patch the
# MANAGED_FILES inline by injecting an entry. Simplest: invoke the
# pull logic directly via the CLI's `pull_file` function if exported,
# otherwise call `blueprint pull fixture-target.md` with a managed-list
# override via env var.
#
# For now: build a minimal harness that calls the same merge logic the
# CLI uses. The CLI itself is what we're testing — to keep the fixture
# self-contained, we invoke `blueprint pull fixture-target.md` and
# trust the CLI is on PATH (or fall back to the local one).

BLUEPRINT_BIN="$ROOT/scripts/blueprint"
if [ ! -x "$BLUEPRINT_BIN" ]; then
  echo "FAIL: $BLUEPRINT_BIN not executable"
  exit 2
fi

# The CLI's MANAGED_FILES doesn't include fixture-target.md. To test
# without modifying the canonical list, we point fixture-target.md at a
# managed slot temporarily: copy fixture-blueprint.md to a path that IS
# managed (in the blueprint working tree), then arrange the project to
# have a file at the same relative path.
#
# Simpler: use one of the existing skeleton READMEs as the carrier.
# We pick docs/mocks/README.md (already in MANAGED_FILES, low-stakes
# content). Override its content in BOTH the project and a temp clone
# of the blueprint, run the merge, then verify.

# Create a temp blueprint-clone so we don't dirty the real blueprint.
BP_CLONE="$(mktemp -d)/bp-clone"
mkdir -p "$BP_CLONE"
( cd "$ROOT" && git archive HEAD | tar -x -C "$BP_CLONE" )
cp "$BP" "$BP_CLONE/docs/mocks/README.md"

# Put the project version into $WORK at the same relative path.
mkdir -p "$WORK/docs/mocks"
cp "$PROJ_BEFORE" "$WORK/docs/mocks/README.md"

# Initialise the project as a minimal git repo so the CLI's
# `.blueprint-source` check works (and it can compute SHAs etc).
( cd "$WORK" && git init -q && git add . && git -c user.email=test@local -c user.name=test commit -q -m init )

# Point .blueprint-source at the clone so the test is isolated.
cat >"$WORK/.blueprint-source" <<EOF
blueprint_source = $BP_CLONE
bootstrap_sha    = $(git -C "$BP_CLONE" rev-parse HEAD 2>/dev/null || echo "no-sha")
bootstrap_date   = test-fixture
EOF

# Run the pull with --yes so it doesn't prompt.
( cd "$WORK" && "$BLUEPRINT_BIN" pull docs/mocks/README.md --yes ) >/dev/null 2>&1
PULL_EXIT=$?

if [ $PULL_EXIT -ne 0 ]; then
  echo "FAIL: blueprint pull exited $PULL_EXIT"
  exit 1
fi

# Compare the project's docs/mocks/README.md against the expected output.
if ! diff -q "$WORK/docs/mocks/README.md" "$EXPECTED" >/dev/null 2>&1; then
  echo "FAIL: post-pull project file does not match expected."
  echo
  echo "diff (actual vs expected):"
  diff -u "$WORK/docs/mocks/README.md" "$EXPECTED" | head -80
  exit 1
fi

echo "PASS: marker-aware merge produced the expected file byte-for-byte."
echo "       Project outside-marker content preserved; inside-marker content updated."
exit 0
